### ISSUE TITLE
Future and thoughts

### ISSUE THREAD

**Issue by shaggygi** [tunnelvisionlabs/dotnet-trees#39]
I came across this repo today and wanted to know if this might fall into something as described on the following issue: https://github.com/dotnet/corefx/issues/18357

Is this something that might eventually be wrapped into the System.Collections.Immutable packages?

Thanks for any help/thoughts.

**Comment by sharwell** [comment]
I haven't put too much thought into including that specific functionality with this library. However, after an initial implementation stabilizes, I plan to offer this as a replacement for the majority of the System.Collections.Immutable package per dotnet/corefx#1502.

**Comment by sharwell** [comment]
@shaggygi Given the amount of remaining work to implement the base collections, I won't be able to create API proposals specific to this topic. If you believe you've found an API that would work well in these situations, feel free to post it up as a new proposal for discussion.
